#spring:
#  datasource:
#    password: none
#    url: url-of-db
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#    show-sql: true

#
#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-alias: skipper
#    key-store: Server/skipper.keystore
#    key-store-type: jks
#    key-store-password: skipper
#    key-password: skipper
#

